#@ shell = /bin/bash
#@ environment = COPY_ALL
#@ job_name = shapeit_run
#@ job_type = serial
#@ group = nesi
#@ class = default
#@ notification = never
#@ wall_clock_limit = 
#@ resourcse = ConsumableMemory(gb) ConsumableVirtualMemory(gb)
#@ output = $(jobid).out 
#@ error = $(jobid).err
#@ parrallel_threads = 
#@ notification = complete
#@ queue

ulimit -v  -m 

shapeit --input-ped   -M  --output-max  --thread  
